kind: Service
apiVersion: v1
metadata:
  name: go-web
  labels:
    app: go-web
spec:
  selector:
    run: go-web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: go-web
        app: go-web
    spec:
      containers:
      - name: go-web
        image: prevedex2.azurecr.io/go-web
        env:
        - name: HOST_PLATFORM
          value: "ACS Kubernetes"
        - name: BACK_COLOR
          value: "green"
        ports:
          - containerPort: 8080
      imagePullSecrets:
         - name: registrykey-stage
